In [ ]:
# StabVSP Use Case 
# Version: v2
# Author: LI Zhikai
import numpy as np
import re
from pathlib import Path
import pandas as pd
import math
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import cm
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
mpl.rcParams.update({'figure.dpi':150})
# path = mpl.rcParams['datapath']
from io import StringIO
import os
import warnings
warnings.filterwarnings('ignore')
import stabvsp as sv

#theta, gamma in degrees
thetaR=5 # [degree]
gammaR=3 # [degree]

In_dir=[
        # 'CG(0.4 0)AoA(-10 +15)b0V12',
        # # 'CG(0.4 -0.03)AoA(-10 +15)b0V12',
        # 'CG(0.4 -0.05)AoA(-10 +15)b0V12','CG(0.4 -0.10)AoA(-10 +15)b0V12',
        # 'CG(0.4 -0.15)AoA(-10 +15)b0V12','CG(0.4 -0.20)AoA(-10 +15)b0V12',
        # 'CG(0.4 -0.25)AoA(-10 +15)b0V12','CG(0.4 -0.30)AoA(-10 +15)b0V12',
        # 'CG(0.4 -0.35)AoA(-10 +15)b0V12','CG(0.4 -0.40)AoA(-10 +15)b0V12',
        # 'CG(0.4 -0.45)AoA(-10 +15)b0V12','CG(0.4 -0.50)AoA(-10 +15)b0V12',

        'CG(0.45 0)AoA(-10 +15)b0V12'#,'CG(0.45 -0.05)AoA(-10 +15)b0V12',
        # 'CG(0.45 -0.10)AoA(-10 +15)b0V12' ,'CG(0.45 -0.15)AoA(-10 +15)b0V12',
        # 'CG(0.45 -0.20)AoA(-10 +15)b0V12' ,
        # 'CG(0.45 -0.25)AoA(-10 +15)b0V12','CG(0.45 -0.30)AoA(-10 +15)b0V12',
        # # 'CG(0.45 -0.325)AoA(-10 +15)b0V12',
        # 'CG(0.45 -0.35)AoA(-10 +15)b0V12','CG(0.45 -0.40)AoA(-10 +15)b0V12',
        # 'CG(0.45 -0.45)AoA(-10 +15)b0V12','CG(0.45 -0.50)AoA(-10 +15)b0V12'
        # 'CG(0.50 -0.0)AoA(-10 +15)b0V12' ,'CG(0.50 -0.05)AoA(-10 +15)b0V12',
        # 'CG(0.50 -0.10)AoA(-10 +15)b0V12','CG(0.50 -0.15)AoA(-10 +15)b0V12',
        # 'CG(0.50 -0.20)AoA(-10 +15)b0V12','CG(0.50 -0.25)AoA(-10 +15)b0V12',
        # 'CG(0.50 -0.30)AoA(-10 +15)b0V12' 
        ]
mass_in_name="Mass_Inertia_out.txt"
stabFileName='PR6_001_DegenGeom'


In [2]:
DataCon=[]

for icon in range(len(In_dir)):
    massname_with_dir='./'+In_dir[icon]+'/'+mass_in_name
    stabname_with_dir='./'+In_dir[icon]+'/'+stabFileName+'.stab'
    pstabname_with_dir='./'+In_dir[icon]+'/'+stabFileName+'.pstab'
    qstabname_with_dir='./'+In_dir[icon]+'/'+stabFileName+'.qstab'
    rstabname_with_dir='./'+In_dir[icon]+'/'+stabFileName+'.rstab'
    # print(massname_with_dir)
    massProp=sv.readmass(massname_with_dir)
    stabCases=sv.ReadStabFile(stabname_with_dir)
    DataCon.append(sv.StabDataCon(massProp,stabCases,In_dir[icon]))
    sv.Read_Add_DynCase(pstabname_with_dir,DataCon[icon].StabDataList)
    sv.Read_Add_DynCase(qstabname_with_dir,DataCon[icon].StabDataList)
    sv.Read_Add_DynCase(rstabname_with_dir,DataCon[icon].StabDataList)
    sv.Cal_Lat_Lgl(DataCon[icon].MassProp,DataCon[icon].StabDataList,thetaR,gammaR)
    sv.Cal_Dyn_Coefs_Batch(DataCon[icon].StabDataList)

# print(DataCon[4].StabDataList)
    

File ./CG(0.45 0)AoA(-10 +15)b0V12/PR6_001_DegenGeom.stab has been read successfully.
File ./CG(0.45 0)AoA(-10 +15)b0V12/PR6_001_DegenGeom.pstab has been read successfully.
File ./CG(0.45 0)AoA(-10 +15)b0V12/PR6_001_DegenGeom.qstab has been read successfully.
File ./CG(0.45 0)AoA(-10 +15)b0V12/PR6_001_DegenGeom.rstab has been read successfully.
CGz 0.0 AoA -10.0000000
spiral 145.43101895079974
dutch roll 0.2805590663498254
[[-2.60457466e-01  2.14127794e+01  0.00000000e+00 -9.79655574e+00]
 [ 3.41553791e-01 -1.21034653e+01  8.82508026e-01 -4.27846442e-02]
 [ 1.46609035e+00 -5.22807430e+01  1.94436280e+00 -1.57835860e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]]
CGz 0.0 AoA -9.0000000
spiral 155.7057248179097
dutch roll 0.3616858779751481
[[ -0.22666675  19.87466582   0.          -9.79655574]
 [  0.3066005  -11.79159774   0.88310315  -0.04278464]
 [  0.18388053  -5.72990889  -1.3091599    0.        ]
 [  0.           0.           1.           0.        ]]
CGz 0

In [ ]:
cmapBW30=plt.get_cmap('binary',30)
colorBW30=cmapBW30([range(30)])
print(colorBW30[0][10][0:3])
viridis= mpl.colormaps['viridis_r'].resampled(40)
colorVR32= viridis(range(40))
# # colorBW30=colorBW30[:,0:3]



mkr_list=['x','^','o','1','*','d','s','+','h','p','p']
lin_list=['-',':','-.','--']
lbl_list=['$z_{CG}=0$','$z_{CG}=24\%MAC$','$z_{CG}=48\%MAC$',
          '$z_{CG}=72\%MAC$','$z_{CG}=95\%MAC$','$z_{CG}=119\%MAC$',
          '$z_{CG}=143\%MAC$','$z_{CG}=167\%MAC$','$z_{CG}=190\%MAC$',
          '$z_{CG}=214\%MAC$','$z_{CG}=238\%MAC$']

In [ ]:
fig, ax1 = plt.subplots()

for icon in [0]:
    StabData=DataCon[icon].StabDataList;
    for icase in range(0,len(StabData)):
        # range(15,len(StabData)-10):
        stabcase=StabData[icase]
        # CaseColor=colorBW30[0][icase+3][0:3]
        CaseColor=colorVR32[icase+2]#[0:3]
        if(icase==10):
            CaseColor='r'
        elif(icase>10):
            CaseColor=colorVR32[icase+13]
        # plt.plot(EigValues.real, EigValues.imag,
        #          mkr, color=color,ms=4)
        sv.PlotStabScatter(ax1,stabcase.EigValuesLtrl,
                        CaseColor,mkr_list[icon % 10]
                        )
        
        # plt.plot(stabcase.EigValuesLtrl.real,stabcase.EigValuesLtrl.imag,
        #          marker=mkr_list[icon % 7], color=CaseColor,ms=4,linewidth=0)
# ax1.legend(labels=lbl_list)
# ax1.scatter(0,0,c='r',marker='+')
plt.grid(color = [0.9,0.9,0.9], linestyle = '--', linewidth = 0.5)
plt.xlabel('Re')
plt.ylabel('Im')
plt.show()
# figFileName='P6_CG('+str(round(MassProperties['CGx'],3))+' '+str(round(MassProperties['CGz'],3))+')_Lateral.png'
# print(figFileName)
# plt.savefig(figFileName,bbox_inches='tight')